In [3]:
my_dict = {
    "PC": 0,
    "MAC": 1,
    "IPAD": 2,
    "PHONE":3
}

In [5]:
my_dict["MAC"]

1

In [12]:
columns = []
columns.append(my_dict)

In [13]:
columns

[{'PC': 0, 'MAC': 1, 'IPAD': 2, 'PHONE': 3}]

In [14]:
for i in columns:
    columns.pop()

In [15]:
columns

[]

In [43]:
mevcut_sutunlar = ["yas", "gelir", "cinsiyet", "id_no"]

In [38]:
# temiz_sutunlar = mevcut_sutunlar.remove("id_no")
# bu kod sonucunda temiz_sutunlar boş döner. çünkü remove fonksiyonu geriye bir lsite dööndürmez.
# sadece eleman silme işlemi yapar.

In [44]:
clear_list = [col for col in mevcut_sutunlar if col != "id_no"]

In [45]:
clear_list

['yas', 'gelir', 'cinsiyet']

In [46]:
import pandas as pd

In [133]:
data = {
    "yas": [15,20,22,24,28],
    "gelir": [20000, 28000, 35000, 450000, 66000],
    "cinsiyet": ["K", "E", "E", "E","K"],
    "id_no": [120,106,204,145,160]
}

In [134]:
df = pd.DataFrame(data)

In [135]:
df

   yas   gelir cinsiyet  id_no
0   15   20000        K    120
1   20   28000        E    106
2   22   35000        E    204
3   24  450000        E    145
4   28   66000        K    160

In [136]:
df_new = df.drop("id_no", axis = 1) # burada inplace = True ile df değişkeni None değerini aldı
df_new

   yas   gelir cinsiyet
0   15   20000        K
1   20   28000        E
2   22   35000        E
3   24  450000        E
4   28   66000        K

In [137]:
df_changed = df.drop(["yas","gelir"], axis = 1)

In [138]:
df_changed

  cinsiyet  id_no
0        K    120
1        E    106
2        E    204
3        E    145
4        K    160

In [139]:
df

   yas   gelir cinsiyet  id_no
0   15   20000        K    120
1   20   28000        E    106
2   22   35000        E    204
3   24  450000        E    145
4   28   66000        K    160

In [140]:
silinecekler = ["id_no", "cinsiyet"]
df_son = df.drop(silinecekler, axis = 1)

In [141]:
df_son

   yas   gelir
0   15   20000
1   20   28000
2   22   35000
3   24  450000
4   28   66000

In [142]:
df

   yas   gelir cinsiyet  id_no
0   15   20000        K    120
1   20   28000        E    106
2   22   35000        E    204
3   24  450000        E    145
4   28   66000        K    160

In [143]:
for col in df.columns:
    if col.endswith("no"):
        df.drop(col, axis = 1, inplace = True)

In [144]:
df

   yas   gelir cinsiyet
0   15   20000        K
1   20   28000        E
2   22   35000        E
3   24  450000        E
4   28   66000        K

In [126]:
silinecekler = [col for col in df.columns if col.endswith("t")]
df = df.drop(silinecekler, axis = 1)

In [127]:
df

   yas   gelir
0   15   20000
1   20   28000
2   22   35000
3   24  450000
4   28   66000

In [128]:
[col.upper() for col in df.columns]
#yapılacak işlem (sonuc) baştaki değerdir

['YAS', 'GELIR']

In [129]:
[len(col) for col in df.columns]

[3, 5]

In [150]:
df_deneme = df.rename(columns = {"getir": " getir  "})

In [151]:
df_deneme

   yas   gelir cinsiyet
0   15   20000        K
1   20   28000        E
2   22   35000        E
3   24  450000        E
4   28   66000        K

In [152]:
df_deneme.columns

Index(['yas', 'gelir', 'cinsiyet'], dtype='object')

In [148]:
df

   yas   gelir cinsiyet
0   15   20000        K
1   20   28000        E
2   22   35000        E
3   24  450000        E
4   28   66000        K

In [153]:
df_deneme["gelir"]

0     20000
1     28000
2     35000
3    450000
4     66000
Name: gelir, dtype: int64